# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: mariabonita_development
  pool: 5
  username:
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: mariabonita_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: mariabonita_production
  pool: 5
  username:
  password:

cucumber:
  <<: *TEST
