default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: mariabonita_development
  host: localhost
  pool: 5
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: mariabonita_test
  pool: 5
  host: localhost
  username: <%= ENV["DATABASE_USER"] || "postgres" %>
  password: <%= ENV["DATABASE_PASSWORD"] || "postgres" %>

production:
  adapter: postgresql
  encoding: utf8
  database: mariabonita_production
  pool: 5

cucumber:
  <<: *TEST
